export const categories = [
  { id: 1, name: "Pain Relief" },
  { id: 2, name: "Cough Syrup" },
  { id: 3, name: "Cold and Flu" },
  { id: 4, name: "Allergy Medications" },
  { id: 5, name: "Digestive Health" },
  { id: 6, name: "First Aid" },
  { id: 7, name: "Cough Suppressants" },
  { id: 8, name: "Antibiotics" },
  { id: 9, name: "Antiseptics" },
  { id: 10, name: "Anti-Inflammatory Medications" },
  { id: 11, name: "Vitamins and Supplements" },
  // "Skin Care",
  // "Eye Care",
  // "Ear Care",
  // "Dental Care",
  // "Women's Health",
  // "Men's Health",
  // "Children's Health",
  // "Blood Pressure Medications",
  // "Diabetes Management",
  // "Respiratory Medications",
  // "Muscle Relaxants",
  // "Antacids",
  // "Laxatives",
  // "Weight Management",
  // "Sleep Aids",
  // "Smoking Cessation",
  // "Fertility Medications",
  // "Wound Care",
  // "Incontinence Products",
  // "Foot Care",
  // "Travel Health",
  // "Sunscreen and UV Protection",
  // "Herbal and Alternative Medicines",
  // "Prescription Medications",
  // "Over-the-Counter (OTC) Medications",
  // "Medical Devices",
  // "Health Monitors",
  // "Rehabilitation and Orthopedic Aids",
  // "Homeopathic Remedies",
  // "Dietary and Nutritional Products",
  // "Personal Hygiene Products",
  // "Medical Supplies and Equipment",
];
