export const categories = [
  "Pain Relief",
  "Cold and Flu",
  "Allergy Medications",
  "Digestive Health",
  "First Aid",
  "Cough Suppressants",
  "Antibiotics",
  "Antiseptics",
  "Anti-Inflammatory Medications",
  "Vitamins and Supplements",
  "Skin Care",
  "Eye Care",
  "Ear Care",
  "Dental Care",
  "Women's Health",
  "Men's Health",
  "Children's Health",
  "Blood Pressure Medications",
  "Diabetes Management",
  "Respiratory Medications",
  "Muscle Relaxants",
  "Antacids",
  "Laxatives",
  "Weight Management",
  "Sleep Aids",
  "Smoking Cessation",
  "Fertility Medications",
  "Wound Care",
  "Incontinence Products",
  "Foot Care",
  "Travel Health",
  "Sunscreen and UV Protection",
  "Herbal and Alternative Medicines",
  "Prescription Medications",
  "Over-the-Counter (OTC) Medications",
  "Medical Devices",
  "Health Monitors",
  "Rehabilitation and Orthopedic Aids",
  "Homeopathic Remedies",
  "Dietary and Nutritional Products",
  "Personal Hygiene Products",
  "Medical Supplies and Equipment",
];
